{{- $name := "check-memory-requests-equals-limits" }}
{{- if eq (include "kyverno-additional-policies.podSecurityRecommend" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-additional-policies.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: The memory limits should equal the requests.
    policies.kyverno.io/category: Recommend
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Pods which have memory limits equal to requests are given a QoS class of Guaranteed
      which is the highest schedulable class. This policy checks that all containers in
      a given Pod have memory requests equal to limits.
  labels: {{ include "kyverno-additional-policies.labels" . | nindent 4 }}
spec:
  {{- with index .Values "validationFailureActionByPolicy" $name }}
  validationFailureAction: {{ toYaml . }}
  {{- else }}
  validationFailureAction: {{ .Values.validationFailureAction }}
  {{- end }}
  {{- with concat (index .Values "validationFailureActionOverrides" "all") (default list (index .Values "validationFailureActionOverrides" $name)) }}
  validationFailureActionOverrides: {{ toYaml . | nindent 4 }}
  {{- end }}
  failurePolicy: {{ .Values.failurePolicy }}
  background: false
  rules:
    - name: memory-requests-equal-limits-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - DaemonSet
                - StatefulSet
                - Job
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        message: "resources.requests.memory must be equal to resources.limits.memory"
        deny:
          conditions:
            any:
              - key: "{{ `{{request.object.spec.template.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}`}}"
                operator: NotEquals
                value: 0
    - name: memory-requests-equal-limits-pod
      match:
        any:
          - resources:
              kinds:
                - Pod
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        message: "resources.requests.memory must be equal to resources.limits.memory"
        deny:
          conditions:
            any:
              - key: "{{ `{{request.object.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}`}}"
                operator: NotEquals
                value: 0
    - name: memory-requests-equal-limits-cronjob
      match:
        any:
          - resources:
              kinds:
                - CronJob
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        message: "resources.requests.memory must be equal to resources.limits.memory"
        deny:
          conditions:
            any:
              - key: "{{ `{{request.object.spec.jobTemplate.spec.template.spec.containers[?resources.requests.memory!=resources.limits.memory] | length(@) }}`}}"
                operator: NotEquals
                value: 0
{{- end }}
