{{- $name := "aws-load-balancer-controller" }}
{{- if .Values.applications.awsLoadBalancerController.install }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- with .Values.applications.awsLoadBalancerController.additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.applications.awsLoadBalancerController.additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $name }}
  namespace: {{ .Values.applications.awsLoadBalancerController.namespace | default "kube-system" | quote}}
  {{- include "finalizers" . | nindent 2 }}
spec:
  project: {{ .Values.applications.awsLoadBalancerController.project | default "default" | quote }}
  {{- if .Values.applications.awsLoadBalancerController.sources }}
  {{- with .Values.applications.awsLoadBalancerController.sources }}
  sources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ else }}
  source:
    {{- include "awsLoadBalancerController.source" . | nindent 4 }}
  {{- end }}
  {{- include "destination" . | nindent 2 }}
  {{- with .Values.applications.awsLoadBalancerController.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.applications.awsLoadBalancerController.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.applications.awsLoadBalancerController.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.applications.awsLoadBalancerController.info }}
  info:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}