{{- $name := "disallow-ingress-nginx-custom-snippets" }}
{{- if eq (include "kyverno-additional-policies.podSecurityOnNginx" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-additional-policies.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- with .Values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
    {{- end }}
    policies.kyverno.io/title: Disallow Custom Snippets
    policies.kyverno.io/category: Security, NGINX Ingress
    policies.kyverno.io/subject: ConfigMap, Ingress
    policies.kyverno.io/minversion: "1.6.0"
    kyverno.io/kyverno-version: "1.6.0"
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Users that can create or update ingress objects can use the custom snippets
      feature to obtain all secrets in the cluster (CVE-2021-25742). This policy
      disables allow-snippet-annotations in the ingress-nginx configuration and
      blocks *-snippet annotations on an Ingress.
      See: https://github.com/kubernetes/ingress-nginx/issues/7837
  labels: {{ include "kyverno-additional-policies.labels" . | nindent 4 }}
spec:
  validationFailureAction: Enforce
  {{- with concat (index .Values "validationFailureActionOverrides" "all") (default list (index .Values "validationFailureActionOverrides" $name)) }}
  validationFailureActionOverrides: {{ toYaml . | nindent 4 }}
  {{- end }}
  background: {{ .Values.background }}
  failurePolicy: {{ .Values.failurePolicy }}
  rules:
    - name: disallow-configmap-enabled-snippet
      match:
        any:
        - resources:
            kinds:
            - ConfigMap
      validate:
        message: "ingress-nginx allow-snippet-annotations must be set to false"
        pattern:
          =(data):
            =(allow-snippet-annotations) : "false"
    - name: disallow-ingress-snippet-annotations
      match:
        any:
        - resources:
            kinds:
            - networking.k8s.io/v1/Ingress
      validate:
        message: "ingress-nginx custom snippets are not allowed"
        pattern:
          metadata:
            =(annotations):
              X(*-snippet): "?*"
{{- end }}
