{{- $name := "add-karpenter-nodeselector" }}
{{- if eq (include "kyverno-additional-policies.podSecurityOnAws" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-additional-policies.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- with .Values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
    {{- end }}
    policies.kyverno.io/title: Add Karpenter nodeSelector
    policies.kyverno.io/category: Karpenter, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Selecting the correct Node(s) provisioned by Karpenter is a way to specify
      the appropriate resource landing zone for a workload. This policy injects a
      nodeSelector map into the Pod based on the Namespace type where it is deployed.
  labels: {{ include "kyverno-additional-policies.labels" . | nindent 4 }}
spec:
  rules:
    - name: add-medium
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  type: medium
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              kubernetes.io/arch: amd64
              karpenter.sh/capacity-type: spot
    - name: add-large
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  type: large
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              kubernetes.io/arch: amd64
              karpenter.sh/capacity-type: on-demand
{{- end }}
