{{- $configMaps := .Values.configMaps -}}
{{- range $configMap := $configMaps }}
{{- if and $configMap.enabled (eq $configMap.name "envoyfilter") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-maintainer.name" $ }}-{{ $configMap.name }}-config
  namespace: {{ include "kube-maintainer.namespace" $ }}
data:
{{- if $configMap.data.services }}
{{- range $service := $configMap.data.services }}
  {{ $service.name }}.yaml: |
    apiVersion: networking.istio.io/v1alpha3
    kind: EnvoyFilter
    metadata:
      name: {{ $service.name }}-lua-filter
      namespace: {{ $service.namespace }}
    spec:
      workloadSelector:
        labels:
          app: {{ $service.name }}
      configPatches:
        - applyTo: HTTP_FILTER
          match:
            context: SIDECAR_INBOUND
            listener:
              filterChain:
                filter:
                  name: envoy.filters.network.http_connection_manager
                  subFilter:
                    name: envoy.filters.http.router
          patch:
            operation: INSERT_BEFORE
            value:
              name: envoy.filters.http.lua
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                inline_code: |
                  function envoy_on_request(request_handle)
                    local authority = request_handle:headers():get(":authority") or "no-authority"
                    local bypass_mode = request_handle:headers():get("X-BYPASS-MODE")
                    local path = request_handle:headers():get(":path") or ""
                    local method = request_handle:headers():get(":method") or ""
                    local x_filter = "false"

                    -- OPTIONS 메서드는 모두 허용
                    if string.upper(method) == "OPTIONS" then
                      x_filter = "false"
                    else
                      if authority == "{{ $configMap.data.denyHost }}" then
                        if not bypass_mode or bypass_mode ~= "true" then
                          x_filter = "true"
                        end
                      end
                    end
                    request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "x-filter-target-host", x_filter)
                  end

                  function envoy_on_response(response_handle)
                    local is_target = response_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")["x-filter-target-host"]
                    if is_target == "true" then
                      response_handle:headers():replace(":status", {{ $configMap.data.responseCode }})
                      response_handle:headers():replace("content-type", "application/json")
                      local error_body = {{ $configMap.data.responseBody | quote }}
                      response_handle:body():setBytes(error_body)
                    end
                  end
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}
{{- end }}