{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kube-maintainer.name" . }}-ingress
  namespace: {{ include "kube-maintainer.namespace" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
{{ include "kube-maintainer.labels" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "alb" }}
  # Notice:
  # servicePort: 80 (dfault value) is used in the following line)
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
{{- end }}