apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-maintainer.name" . }}-service
  namespace: {{ include "kube-maintainer.namespace" . }}
  labels:
{{ include "kube-maintainer.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "kube-maintainer.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort | default 80 }}
      targetPort: 5000
