apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-maintainer.serviceAccountName" . }}
  namespace: {{ include "kube-maintainer.namespace" . }}
  labels:
{{ include "kube-maintainer.labels" . | indent 4 }}
{{- if .Values.serviceAccountAnnotations }}
  annotations: {{ toYaml .Values.serviceAccountAnnotations | nindent 4 }}
{{- end }}