{{- $name := "check-vulnerable-kernel" }}
{{- if eq (include "kyverno-additional-policies.podSecurityRecommend" (merge (dict "name" $name) .)) "true" }}
{{- include "kyverno-additional-policies.supportedKyvernoCheck" (dict "top" . "ver" ">= 1.6.0-0") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    {{- with .Values.autogenControllers }}
    pod-policies.kyverno.io/autogen-controllers: {{ . }}
    {{- end }}
    policies.kyverno.io/title: Check Nodes for Vulnerable Kernels like CVE-2022-0185
    policies.kyverno.io/category: Recommend
    policies.kyverno.io/severity: high
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Node
    policies.kyverno.io/description: >-
      Linux CVE-2022-0185 can allow a container escape in Kubernetes if left unpatched.
      The affected Linux kernel versions, at this time, are 5.10.84-1 and 5.15.5-2.
      For more information, refer to https://security-tracker.debian.org/tracker/CVE-2022-0185.
      This policy runs in background mode and flags an entry in the ClusterPolicyReport
      if any Node is reporting one of the affected kernel versions.
  labels: {{ include "kyverno-additional-policies.labels" . | nindent 4 }}
spec:
  {{- with index .Values "validationFailureActionByPolicy" $name }}
  validationFailureAction: {{ toYaml . }}
  {{- else }}
  validationFailureAction: {{ .Values.validationFailureAction }}
  {{- end }}
  {{- with concat (index .Values "validationFailureActionOverrides" "all") (default list (index .Values "validationFailureActionOverrides" $name)) }}
  validationFailureActionOverrides: {{ toYaml . | nindent 4 }}
  {{- end }}
  background: {{ .Values.background }}
  failurePolicy: {{ .Values.failurePolicy }}
  rules:
    - name: kernel-validate
      match:
        any:
          - resources:
              kinds:
                - Node
      {{- with index .Values "policyExclude" $name }}
      exclude:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "policyPreconditions" $name }}
      preconditions:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      validate:
        message: "Kernel is vulnerable to CVEs"
        deny:
          {{- with index .Values "policyOverrides" $name }}
          conditions:
            {{- if .any }}
            any:
              - key: "{{`{{request.object.status.nodeInfo.kernelVersion}}`}}"
                operator: AnyIn
                value:
                  - "5.10.84-1"
                  - "5.15.5-2"
                message: "Kernel is vulnerable to CVE-2022-0185."
            {{- toYaml .any | nindent 12 }}
            {{- else }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
          conditions:
            any:
              - key: "{{`{{request.object.status.nodeInfo.kernelVersion}}`}}"
                operator: AnyIn
                value:
                  - "5.10.84-1"
                  - "5.15.5-2"
                message: "Kernel is vulnerable to CVE-2022-0185."
          {{- end }}
{{- end }}
